server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9000
          predicates:
            - Path=/user-service/auth/logout, /user-service/auth/validate
          filters:
            - AuthFilter
            - RewritePath=/user-service/auth/(?<segment>.*), /auth/${segment}

        - id: product-service
          uri: http://localhost:9001
          predicates:
            - Path=/product-service/favorite/**
          filters:
            - AuthFilter
            - RewritePath=/product-service/favorite/(?<segment>.*), /favorite/$\{segment}

        - id: order-service-auth
          uri: http://localhost:9002
          predicates:
            - Path=/orders/**
          filters:
            - AuthFilter
            - RewritePath=/order-service/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: http://localhost:9000
          predicates:
            - Path=/**
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        - id: product-service
          uri: http://localhost:9001
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/product-service/(?<segment>.*),/$\{segment}

logging:
  pattern:
    console: "%white([%d{yyyy-MM-dd HH:mm:ss}]) %yellow([%thread]) %highlight([%-5level]) %white([%-35logger{35}]) %white(%msg  %n)"
  level:
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.cloud.gateway: TRACE