server:
  port: 9000

eureka:
  instance:
    app name: user-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/earlyBird
    username: admin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    username: jindory8@gmail.com
    password: sbkrdzbmqrrzpigcpj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  data:
    redis:
      host: redis
      port: 6379
      jwtDuration: 600
      emailDuration: 600
jwt:
  key: sakjhfeksfhkjsaefksenbfksebfkjsabfkjsaebfkjsaebfhksjlsajl4nlnal4joi3j5o3nm45lkn23lk5j2l3k5njlk23n532jb532jb5h32b5k325lk23j5lk23jlk23n4lk32n4jlk4njlanflasnelkfnajks3ln4kjn34lk3n2j5klj43nkbefkhsabefkbsebf
  access-token-expiration-minutes: 3600000
  refresh-token-expiration-minutes: 14400000
logging:
  pattern:
    console: "%white([%d{yyyy-MM-dd HH:mm:ss}]) %yellow([%thread]) %highlight([%-5level]) %white([%-35logger{35}]) %white(%msg  %n)"
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
