version: '3.8'

services:
  db:
    container_name: mysql-container
    build:
      context: ..
      dockerfile: docker/dockerfile-mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: earlybirdDB
    ports:
      - "3306:3306"
    networks:
      - app-network
  app:
    container_name: spring-boot-container
    restart: on-failure
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/earlybirdDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge