version: '3.8'

services:
  db:
    container_name: mysql-container
    depends_on:
      - eureka-server
    build:
      context: .
      dockerfile: dockerfile-mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: earlyBird
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - app-network

  eureka-server:
    container_name: spring-boot-eureka-server
    build:
      context: ..
      dockerfile: eureka-server/docker/dockerfile-eureka
    networks:
      - app-network

  app-api-gateway:
    container_name: spring-boot-api-gateway
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ..
      dockerfile: api-gateway/docker/dockerfile-gateway
    networks:
      - app-network

  app-user:
    container_name: spring-boot-user-container
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ..
      dockerfile: user-service/docker/dockerfile-UserService
    networks:
      - app-network

  app-product:
    container_name: spring-boot-product-container
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ..
      dockerfile: product-service/docker/dockerfile-ProductService
    networks:
      - app-network

  app-order:
    container_name: spring-boot-order-container
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ..
      dockerfile: order-service/docker/dockerfile-OrderService
    networks:
      - app-network

networks:
  app-network:
    driver: bridge