# Base image with Gradle
FROM gradle:8.10.1-jdk21 AS build

# 루트 디렉토리의 settings.gradle 파일 복사
COPY ../../settings.gradle /app/settings.gradle
COPY ../build.gradle /app/build.gradle
COPY ../gradle /app/gradle/

COPY ../api-gateway /app/api-gateway

WORKDIR /app/api-gateway
RUN chmod +x gradlew
RUN ./gradlew build -x test

FROM bellsoft/liberica-openjdk-alpine:21.0.5

COPY --from=build /app/api-gateway/build/libs/*.jar /app/api-gateway.jar
COPY --from=build /app/api-gateway/src/main/resources/application.yml /app/application.yml
ENTRYPOINT ["java", "-jar", "/app/api-gateway.jar", "--spring.config.location=file:/app/application.yml"]